export const categories = [
    {
        id:1,
        title: "Electronics",
    },
    {
        id:2,
        title: "Bag",
    },
    {
        id:3,
        title: "Pharmacy",
    },
    {
        id:4,
        title: "Clothing",
    },
    {
        id:5,
        title: "Sporting",
    },
    {
        id:6,
        title: "Toys",
  },
]

export const sliderItems = [
    {
      id: 1,
      img: "https://m.media-amazon.com/images/I/71NxVwAx-PL._SX3000_.jpg",
    },
    {
      id: 2,
      img: "https://images-na.ssl-images-amazon.com/images/G/01/DiscoTec/2022/HOL22/GW/TallHero/HOL22_dt_tallhero_10-14_Gifting_2x._CB607306607_.jpg",
    },
    {
      id: 3,
      img: "https://m.media-amazon.com/images/I/61cTQJfzyaL._SX3000_.jpg",
    },
    {
      id: 4,
      img: "https://m.media-amazon.com/images/I/51so3XR2bLL._SX3000_.jpg",
    }
  ];


  export const popularProducts = [
    {
      id:1,
      category: "Clothing",
      name:"White Men's T-shirt",
      price: "$15",
      img:"https://d3o2e4jr3mxnm3.cloudfront.net/Mens-Jake-Guitar-Vintage-Crusher-Tee_68382_1_lg.png",
    },
    {
      id:2,
      category: "Sporting",
      name:"Men's Shoes AJ",
      price: "$248",
      img:"https://i.ebayimg.com/images/g/4MEAAOSwwL5i~jO7/s-l640.png",
    },
    {
      id:3,
      category: "Clothing",
      name:"Men's Cotton T-shirt",
      price: "$12",
      img:"https://www.prada.com/content/dam/pradanux_products/U/UCS/UCS319/1YOTF010O/UCS319_1YOT_F010O_S_182_SLF.png",
    },
    {
      id:4,
      category: "Toys",
      name:"Lego Creator Toys",
      price: "$50",
      img:"https://i.ebayimg.com/images/g/a04AAOSwiNRiaOra/s-l640.jpg",
    },
    {
      id:5,
      category: "Bag",
      name:"Shopping Bag",
      price: "$5",
      img:"https://images.ctfassets.net/5gvckmvm9289/3BlDoZxSSjqAvv1jBJP7TH/65f9a95484117730ace42abf64e89572/Noissue-x-Creatsy-Tote-Bag-Mockup-Bundle-_4_-2.png",
    },
    {
      id:6,
      category: "Clothing",
      name:"Grey Hat",
      price: "$20",
      img:"https://d3o2e4jr3mxnm3.cloudfront.net/Rocket-Vintage-Chill-Cap_66374_1_lg.png",
    },
    {
      id:7,
      category: "Electronics",
      name:"Omega Swatch Watch",
      price: "$800",
      img:"https://i.ebayimg.com/images/g/gTYAAOSwNfxiqtNy/s-l640.jpg",
    },
    {
      id:8,
      category: "Clothing",
      name:"Women's Winter Coat",
      price: "$60",
      img:"https://www.pngarts.com/files/3/Women-Jacket-PNG-High-Quality-Image.png",
    },
    {
      id:9,
      category: "Electronics",
      name:"Gaming Laptop",
      price: "$815",
      img:"https://i.ebayimg.com/images/g/ef4AAOSwBH5jA6RN/s-l500.jpg",
    },
    {
      id:10,
      category: "Electronics",
      name:"JBL Headphones",
      price: "$150",
      img:"https://i.ebayimg.com/images/g/gdwAAOSwbw1c8FaQ/s-l500.png",
    },
    {
      id:11,
      category: "Electronics",
      name:"PS5",
      price: "$500",
      img:"https://i.ebayimg.com/images/g/yLYAAOSwjB5h6YGz/s-l500.jpg",
    },
    {
      id:12,
      category: "Electronics",
      name:"Xbox series X",
      price: "$500",
      img:"https://i.ebayimg.com/images/g/u-sAAOSw3JhjFblM/s-l640.jpg",
    },
    {
      id:13,
      category: "Electronics",
      name:"Xbox series S",
      price: "$299",
      img:"https://i.ebayimg.com/images/g/pG4AAOSwlPViz0np/s-l500.jpg",
    },

    {
      id:14,
      category: "Electronics",
      name:"Iphone 11",
      price: "$499",
      img:"https://d3d71ba2asa5oz.cloudfront.net/12003181/images/iph11green.jpg",
    },
    {
      id:15,
      category: "Sporting",
      name:"White Men's AJ",
      price: "$299",
      img:"https://i.ebayimg.com/images/g/aLgAAOSwVjdjEDvj/s-l640.png",
    },
    {
      id:16,
      category: "Bag",
      name:"Black School Bag",
      price: "$45",
      img:"https://i.ebayimg.com/images/g/DukAAOSwl5xix135/s-l500.jpg",
    },
  ]

  export const cartProducts = [
    {
      id:1,
      category: "Clothing",
      name:"White Men's T-shirt",
      price: "$15",
      number: 1,
      img:"https://d3o2e4jr3mxnm3.cloudfront.net/Mens-Jake-Guitar-Vintage-Crusher-Tee_68382_1_lg.png",
    },
    {
      id:2,
      category: "Sporting",
      name:"Men's Shoes AJ",
      price: "$248",
      number: 1,
      img:"https://i.ebayimg.com/images/g/4MEAAOSwwL5i~jO7/s-l640.png",
    },
    {
      id:3,
      category: "Clothing",
      name:"Men's Cotton T-shirt",
      price: "$12",
      number: 1,
      img:"https://www.prada.com/content/dam/pradanux_products/U/UCS/UCS319/1YOTF010O/UCS319_1YOT_F010O_S_182_SLF.png",
    },
    {
      id:4,
      category: "Toys",
      name:"Lego Creator Toys",
      price: "$50",
      number: 1,
      img:"https://i.ebayimg.com/images/g/a04AAOSwiNRiaOra/s-l640.jpg",
    },
    {
      id:5,
      category: "Bag",
      name:"Shopping Bag",
      price: "$5",
      number: 1,
      img:"https://images.ctfassets.net/5gvckmvm9289/3BlDoZxSSjqAvv1jBJP7TH/65f9a95484117730ace42abf64e89572/Noissue-x-Creatsy-Tote-Bag-Mockup-Bundle-_4_-2.png",
    },
    {
      id:6,
      category: "Clothing",
      name:"Grey Hat",
      price: "$20",
      number: 1,
      img:"https://d3o2e4jr3mxnm3.cloudfront.net/Rocket-Vintage-Chill-Cap_66374_1_lg.png",
    },
    {
      id:7,
      category: "Electronics",
      name:"Omega Swatch Watch",
      price: "$800",
      number: 1,
      img:"https://i.ebayimg.com/images/g/gTYAAOSwNfxiqtNy/s-l640.jpg",
    },
    {
      id:8,
      category: "Clothing",
      name:"Women's Winter Coat",
      price: "$60",
      number: 1,
      img:"https://www.pngarts.com/files/3/Women-Jacket-PNG-High-Quality-Image.png",
    },
    {
      id:9,
      category: "Electronics",
      name:"Gaming Laptop",
      price: "$815",
      number: 1,
      img:"https://i.ebayimg.com/images/g/ef4AAOSwBH5jA6RN/s-l500.jpg",
    },
    {
      id:10,
      category: "Electronics",
      name:"JBL Headphones",
      price: "$150",
      number: 1,
      img:"https://i.ebayimg.com/images/g/gdwAAOSwbw1c8FaQ/s-l500.png",
    },
    {
      id:11,
      category: "Electronics",
      name:"PS5",
      price: "$500",
      number: 1,
      img:"https://i.ebayimg.com/images/g/yLYAAOSwjB5h6YGz/s-l500.jpg",
    },
    {
      id:12,
      category: "Electronics",
      name:"Xbox series X",
      price: "$500",
      number: 1,
      img:"https://i.ebayimg.com/images/g/u-sAAOSw3JhjFblM/s-l640.jpg",
    },
    {
      id:13,
      category: "Electronics",
      name:"Xbox series S",
      price: "$299",
      number: 1,
      img:"https://i.ebayimg.com/images/g/pG4AAOSwlPViz0np/s-l500.jpg",
    },

    {
      id:14,
      category: "Electronics",
      name:"Iphone 11",
      price: "$499",
      number: 1,
      img:"https://d3d71ba2asa5oz.cloudfront.net/12003181/images/iph11green.jpg",
    },
    {
      id:15,
      category: "Sporting",
      name:"White Men's AJ",
      price: "$299",
      number: 1,
      img:"https://i.ebayimg.com/images/g/aLgAAOSwVjdjEDvj/s-l640.png",
    },
    {
      id:16,
      category: "Bag",
      name:"Black School Bag",
      price: "$45",
      number: 1,
      img:"https://i.ebayimg.com/images/g/DukAAOSwl5xix135/s-l500.jpg",
    },
  ]